table Clients
	lineageTag: 465483e4-2fae-43fb-9f82-a59a967ad0a8

	column 'Id client'
		dataType: string
		lineageTag: 617fa00c-6aab-4538-9e33-c7b3148855e9
		summarizeBy: none
		sourceColumn: Id client

		annotation SummarizationSetBy = Automatic

	column 'Nom client'
		dataType: string
		lineageTag: 640edf5b-5a6c-4bd3-a2af-51f90d03e191
		summarizeBy: none
		sourceColumn: Nom client

		annotation SummarizationSetBy = Automatic

	partition Clients = m
		mode: import
		source =
				let
				    Source = Vente_ref,
				    #"Lignes groupées" = Table.Group(Source, {"Id client", "Nom client"}, {{"Nombre", each Table.RowCount(_), Int64.Type}}),
				    #"Lignes triées" = Table.Sort(#"Lignes groupées",{{"Id client", Order.Ascending}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Lignes triées",{"Nombre"})
				in
				    #"Colonnes supprimées"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

